import { FileText, Trash2, FileCheck2, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

interface PreviewConfirmationProps {
  file: File;
  htmlPreview: string;
  extractedText: string;
  loading: boolean;
  onGenerate: () => void;
  onCancel: () => void;
  formatBytes: (bytes: number, decimals?: number) => string;
}

export function PreviewConfirmation({
  file,
  htmlPreview,
  extractedText,
  loading,
  onGenerate,
  onCancel,
  formatBytes,
}: PreviewConfirmationProps) {
  const wordCount = extractedText.trim() === "" 
    ? 0 
    : extractedText.trim().split(/\s+/).length;

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 items-start">
      
      {/* Action Card (Left Sidebar) */}
      <div className="lg:col-span-1 space-y-6">
        <Card className="border-border/60 shadow-md">
          <CardHeader>
            <CardTitle className="text-lg">Document Info</CardTitle>
            <CardDescription>Verify details before generating article</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-start gap-3 p-3 rounded-lg bg-muted/50 border border-border/40">
              <FileText className="size-6 text-primary shrink-0 mt-0.5" />
              <div className="min-w-0 flex-1">
                <p className="text-sm font-medium text-foreground truncate" title={file.name}>
                  {file.name}
                </p>
                <p className="text-xs text-muted-foreground">
                  {formatBytes(file.size)}
                </p>
              </div>
            </div>

            <div className="space-y-1 text-xs">
              <div className="flex justify-between py-1 border-b border-border/30">
                <span className="text-muted-foreground">Extracted characters:</span>
                <span className="font-semibold text-foreground">{extractedText.length.toLocaleString()}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-border/30">
                <span className="text-muted-foreground">Estimated words:</span>
                <span className="font-semibold text-foreground">
                  {wordCount.toLocaleString()}
                </span>
              </div>
              <div className="flex justify-between py-1">
                <span className="text-muted-foreground">Status:</span>
                <span className="font-semibold text-amber-500 flex items-center gap-1">
                  Pending confirmation
                </span>
              </div>
            </div>
          </CardContent>
          <CardFooter className="flex flex-col gap-2 border-t border-border/40 pt-4">
            <Button 
              onClick={onGenerate} 
              disabled={loading} 
              className="w-full font-medium gap-2"
            >
              <Sparkles className="size-4" />
              Generate Article
            </Button>
            <Button 
              variant="outline" 
              onClick={onCancel} 
              disabled={loading}
              className="w-full text-muted-foreground hover:text-destructive hover:bg-destructive/5 dark:hover:bg-destructive/10"
            >
              <Trash2 className="size-4 mr-2" />
              Cancel & Reset
            </Button>
          </CardFooter>
        </Card>

        <Alert className="bg-primary/5 border-primary/20">
          <FileCheck2 className="size-4 text-primary" />
          <AlertTitle className="text-primary font-semibold text-xs">How It Works</AlertTitle>
          <AlertDescription className="text-xs text-primary/80 leading-relaxed">
            Your text is sent to the AI as rough travel notes. It generates a structured magazine article with intro, body sections, recommendations, ethics notes, and key facts — all streamed back in real-time.
          </AlertDescription>
        </Alert>
      </div>

      {/* Preview Card (Right Area) */}
      <div className="lg:col-span-2">
        <Card className="border-border/60 shadow-md">
          <CardHeader className="border-b border-border/40 pb-4 flex flex-row items-center justify-between">
            <div>
              <CardTitle className="text-lg">Document Preview</CardTitle>
              <CardDescription>Formatted HTML preview generated by Mammoth.js</CardDescription>
            </div>
          </CardHeader>
          <CardContent className="pt-6">
            <ScrollArea className="h-[450px] w-full rounded-md border bg-card/50 p-6">
              <div 
                className="docx-preview select-text" 
                dangerouslySetInnerHTML={{ __html: htmlPreview }} 
              />
            </ScrollArea>
          </CardContent>
        </Card>
      </div>

    </div>
  );
}
