import { useState, useRef, useCallback, type DragEvent, type ChangeEvent } from "react";
import * as mammoth from "mammoth";
import {
  MAX_FILE_SIZE,
  ACCEPTED_FILE_EXTENSIONS,
  ACCEPTED_MIME_TYPES,
} from "../pages/Home/constants";

interface UseDocxUploadReturn {
  /** The currently selected file */
  file: File | null;
  /** HTML preview generated by Mammoth */
  htmlPreview: string;
  /** Raw extracted text from the DOCX */
  extractedText: string;
  /** Whether a file is currently being dragged over the drop zone */
  isDragging: boolean;
  /** Whether Mammoth is currently parsing the file */
  loading: boolean;
  /** Error message from file validation or parsing */
  error: string | null;
  /** Whether the upload was successful (legacy direct-upload flow) */
  uploadSuccess: boolean;
  /** Ref for the hidden file input element */
  fileInputRef: React.RefObject<HTMLInputElement | null>;
  /** Set an error message externally */
  setError: (error: string | null) => void;
  /** Drag over handler */
  handleDragOver: (e: DragEvent<HTMLDivElement>) => void;
  /** Drag leave handler */
  handleDragLeave: () => void;
  /** Drop handler */
  handleDrop: (e: DragEvent<HTMLDivElement>) => void;
  /** File input change handler */
  handleFileChange: (e: ChangeEvent<HTMLInputElement>) => void;
  /** Trigger the hidden file input click */
  triggerFileInput: () => void;
  /** Reset all upload state */
  resetUpload: () => void;
  /** Format bytes to human-readable string */
  formatBytes: (bytes: number, decimals?: number) => string;
}

export function useDocxUpload(): UseDocxUploadReturn {
  const [file, setFile] = useState<File | null>(null);
  const [htmlPreview, setHtmlPreview] = useState<string>("");
  const [extractedText, setExtractedText] = useState<string>("");
  const [isDragging, setIsDragging] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [uploadSuccess, setUploadSuccess] = useState<boolean>(false);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const formatBytes = useCallback((bytes: number, decimals = 2) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const dm = decimals < 0 ? 0 : decimals;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
  }, []);

  const validateAndProcessFile = useCallback((selectedFile: File) => {
    setError(null);
    setUploadSuccess(false);

    // Validate size limit (10MB)
    if (selectedFile.size > MAX_FILE_SIZE) {
      setError(`File size exceeds the 10MB limit (Current size: ${formatBytes(selectedFile.size)}). Please select a smaller file.`);
      return;
    }

    // Validate file extension/type
    const fileExtension = selectedFile.name.split('.').pop()?.toLowerCase() || '';
    const isValidExtension = ACCEPTED_FILE_EXTENSIONS.includes(fileExtension);
    const isValidMimeType = ACCEPTED_MIME_TYPES.includes(selectedFile.type);

    if (!isValidExtension && !isValidMimeType) {
      setError("Only .docx files are supported. Please select a valid Word document.");
      return;
    }

    setFile(selectedFile);
    setLoading(true);

    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        const arrayBuffer = e.target?.result as ArrayBuffer;
        if (!arrayBuffer) {
          throw new Error("Unable to read the file content.");
        }

        // Generate HTML preview using Mammoth
        const previewResult = await mammoth.convertToHtml({ arrayBuffer });
        setHtmlPreview(previewResult.value || "<p class='text-muted-foreground italic'>This document has no printable or previewable content.</p>");

        // Extract raw text only
        const textResult = await mammoth.extractRawText({ arrayBuffer });
        setExtractedText(textResult.value || "");
      } catch (err) {
        console.error("Error parsing DOCX file with Mammoth:", err);
        const errorMessage = err instanceof Error ? err.message : "An error occurred while parsing the Word file. Please try again.";
        setError(errorMessage);
        setFile(null);
      } finally {
        setLoading(false);
      }
    };

    reader.onerror = () => {
      setError("Failed to read the file from your device.");
      setFile(null);
      setLoading(false);
    };

    reader.readAsArrayBuffer(selectedFile);
  }, [formatBytes]);

  const handleDragOver = useCallback((e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback(() => {
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback((e: DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      validateAndProcessFile(e.dataTransfer.files[0]);
    }
  }, [validateAndProcessFile]);

  const handleFileChange = useCallback((e: ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      validateAndProcessFile(e.target.files[0]);
    }
  }, [validateAndProcessFile]);

  const triggerFileInput = useCallback(() => {
    fileInputRef.current?.click();
  }, []);

  const resetUpload = useCallback(() => {
    setFile(null);
    setHtmlPreview("");
    setExtractedText("");
    setError(null);
    setUploadSuccess(false);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  }, []);

  return {
    file,
    htmlPreview,
    extractedText,
    isDragging,
    loading,
    error,
    uploadSuccess,
    fileInputRef,
    setError,
    handleDragOver,
    handleDragLeave,
    handleDrop,
    handleFileChange,
    triggerFileInput,
    resetUpload,
    formatBytes,
  };
}
